// This file is generated by Prismic local builder. Update with care!

export { default as FeaturedImage } from './FeaturedImage'
export { default as FullWidthImgSlice } from './FullWidthImgSlice'
export { default as HeroSlice } from './HeroSlice'
export { default as ImgGallerySlice } from './ImgGallerySlice'
export { default as QuoteSlice } from './QuoteSlice'
export { default as TextSlice } from './TextSlice'
